# Generated by Django 2.0.7 on 2018-07-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('firstapp', '0003_auto_20180711_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='pwd',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='people',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
