# Generated by Django 2.0.7 on 2018-07-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('firstapp', '0004_auto_20180711_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
