# Generated by Django 2.0.7 on 2018-07-14 01:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('firstapp', '0005_auto_20180713_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
